import { users, interventions } from '@/lib/data';
export default function AdminPage() {
  const active = users.filter(u => !u.lastActive.includes('31')).length;
  return <section className="section container">
    <div className="page-heading"><span className="eyebrow">Administrator portal</span><h1>Platform usage and coaching intelligence</h1><p>Monitor adoption, engagement and evidence-based coaching intervention needs across organisations.</p></div>
    <div className="metric-grid"><div className="metric"><span>Total users</span><strong>246</strong><small>Across 8 organisations</small></div><div className="metric"><span>Active this month</span><strong>184</strong><small>74.8% engagement</small></div><div className="metric"><span>Intervention alerts</span><strong>{interventions.length}</strong><small>2 high priority</small></div><div className="metric"><span>Licensed coaches</span><strong>19</strong><small>14 active this week</small></div></div>
    <div className="two-column">
      <section className="panel"><h2>Usage by leadership theme</h2>{[['Values Driven',88],['Cultural Competence',64],['Performance Centred',77],['Strategic & Integrative',71],['People Oriented',59],['Personal Development',82]].map(([name,value]) => <div className="bar-row" key={name}><div><span>{name}</span><strong>{value}%</strong></div><div className="bar"><span style={{width:`${value}%`}} /></div></div>)}</section>
      <section className="panel"><h2>Coaching intervention summary</h2><div className="risk-summary"><div><span className="dot red"></span><strong>2 High</strong><small>Immediate coaching review</small></div><div><span className="dot amber"></span><strong>2 Medium</strong><small>Monitor and follow up</small></div><div><span className="dot green"></span><strong>{active - 2} Stable</strong><small>Progressing as expected</small></div></div></section>
    </div>
    <div className="panel table-panel"><div className="panel-title"><div><h2>User engagement overview</h2><p>Demonstration data for the multi-organisation administrator view.</p></div><button className="button secondary" type="button">Export report</button></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Organisation</th><th>Coach</th><th>Progress</th><th>Avg.</th><th>Priority</th><th>Risk</th><th>Last active</th></tr></thead><tbody>{users.map(u => <tr key={u.name}><td><strong>{u.name}</strong></td><td>{u.organisation}</td><td>{u.coach}</td><td>{u.progress}%</td><td>{u.score}</td><td>{u.priority}</td><td><span className={`status ${u.risk}`}>{u.risk}</span></td><td>{u.lastActive}</td></tr>)}</tbody></table></div></div>
    <div className="panel"><h2>Coaching Intervention Centre</h2>{interventions.map(i => <article className="intervention" key={i.user}><div><span className={`status ${i.level === 'High' ? 'red' : 'amber'}`}>{i.level}</span><strong>{i.user}</strong><span className="status neutral">{i.status}</span></div><p>{i.reason}</p><small>{i.recommendation}</small></article>)}</div>
  </section>;
}
